openapi: 3.0.3
info:
  title: My Hotel Assistant API - Payment
  description: Payment management endpoints
  version: 1.0.0
  contact:
    name: API Support
    email: support@myhotelassistant.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.myhotelassistant.com
    description: Production server

tags:
  - name: Payment
    description: Payment processing endpoints

paths:
  /payment/create-checkout-session:
    post:
      tags:
        - Payment
      summary: Create Stripe checkout session
      description: Create a new Stripe checkout session for payment processing
      operationId: createCheckoutSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCheckoutSessionRequest'
      responses:
        '201':
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCheckoutSessionResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CreateCheckoutSessionRequest:
      type: object
      required:
        - amountCents
        - successUrl
        - cancelUrl
      properties:
        amountCents:
          type: integer
          format: int64
          example: 5000
          description: Amount in cents
        currency:
          type: string
          default: "usd"
          example: "usd"
        successUrl:
          type: string
          example: "http://localhost:5173/payment/success"
        cancelUrl:
          type: string
          example: "http://localhost:5173/payment/cancel"
        customerEmail:
          type: string
          format: email
          nullable: true
          example: "customer@example.com"
        orderDescription:
          type: string
          default: "Hotel Services Order"
          example: "Hotel Services Order"
        cartItems:
          type: string
          nullable: true
          example: "Room cleaning, Laundry service"

    CreateCheckoutSessionResponse:
      type: object
      properties:
        url:
          type: string
          example: "https://checkout.stripe.com/pay/cs_test_..."
        sessionId:
          type: string
          example: "cs_test_a1b2c3d4e5f6g7h8i9j0"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
        status:
          type: integer
          example: 400
        timestamp:
          type: string
          format: date-time

