openapi: 3.0.3
info:
  title: My Hotel Assistant API - Reservations
  description: Reservation management endpoints
  version: 1.0.0
  contact:
    name: API Support
    email: support@myhotelassistant.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.myhotelassistant.com
    description: Production server

tags:
  - name: Reservations
    description: Hotel reservation management endpoints

paths:
  /reservations:
    get:
      tags:
        - Reservations
      summary: Get all reservations
      description: Retrieve all reservations (Employee only)
      operationId: getAllReservations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required

    post:
      tags:
        - Reservations
      summary: Create a new reservation
      description: Create a new room reservation (Guest only)
      operationId: createReservation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationCreateDTO'
      responses:
        '201':
          description: Reservation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationEntity'
        '400':
          description: Invalid reservation data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Guest role required

  /reservations/{status}:
    get:
      tags:
        - Reservations
      summary: Get reservations by status
      description: Retrieve all reservations with specific status (Employee only)
      operationId: getAllReservationsWithStatus
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
            enum: [pending, approved, rejected, cancelled, checked_in, checked_out]
      responses:
        '200':
          description: Successfully retrieved reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required

  /reservations/mine:
    get:
      tags:
        - Reservations
      summary: Get my reservations
      description: Retrieve reservations for the authenticated guest
      operationId: getMyReservations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Guest role required

  /reservations/{reservationId}/cancel:
    patch:
      tags:
        - Reservations
      summary: Cancel my reservation
      description: Cancel own reservation (Guest only)
      operationId: cancelMyReservation
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reservation cancelled successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Reservation not found

  /reservations/{reservationId}/reject:
    patch:
      tags:
        - Reservations
      summary: Reject reservation
      description: Reject a guest reservation (Employee only)
      operationId: rejectGuestReservation
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RejectionReasonDTO'
      responses:
        '200':
          description: Reservation rejected successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required
        '404':
          description: Reservation not found

  /reservations/{reservationId}/approve:
    patch:
      tags:
        - Reservations
      summary: Approve reservation
      description: Approve a guest reservation (Employee only)
      operationId: approveGuestReservation
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reservation approved successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required
        '404':
          description: Reservation not found

  /reservations/{reservationId}/check-in:
    patch:
      tags:
        - Reservations
      summary: Check-in guest
      description: Check-in a guest for their reservation (Employee only)
      operationId: checkInGuestReservation
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
        - name: paid
          in: query
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: Guest checked in successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required
        '404':
          description: Reservation not found

  /reservations/{reservationId}/check-out:
    patch:
      tags:
        - Reservations
      summary: Check-out guest
      description: Check-out a guest from their reservation (Employee only)
      operationId: checkOutGuestReservation
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Guest checked out successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Employee role required
        '404':
          description: Reservation not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ReservationEntity:
      type: object
      properties:
        id:
          type: string
          example: "res123"
        roomNumber:
          type: string
          example: "101"
        guestUsername:
          type: string
          example: "john.doe"
        guestsCount:
          type: integer
          example: 2
        checkIn:
          type: string
          format: date
          example: "2024-01-15"
        checkOut:
          type: string
          format: date
          example: "2024-01-20"
        specialRequests:
          type: string
          nullable: true
          example: "Late check-in"
        status:
          type: string
          example: "pending"
        createdAt:
          type: string
          format: date-time

    ReservationDTO:
      allOf:
        - $ref: '#/components/schemas/ReservationEntity'
        - type: object
          properties:
            guestFullName:
              type: string
              nullable: true
              example: "John Doe"
            guestEmail:
              type: string
              nullable: true
              example: "john.doe@example.com"
            roomStandard:
              type: string
              example: "Deluxe"

    ReservationCreateDTO:
      type: object
      required:
        - roomNumber
        - guestUsername
        - guestsCount
        - checkIn
        - checkOut
      properties:
        roomNumber:
          type: string
          example: "101"
        guestUsername:
          type: string
          example: "john.doe"
        guestsCount:
          type: integer
          minimum: 1
          example: 2
        checkIn:
          type: string
          format: date
          example: "2024-01-15"
        checkOut:
          type: string
          format: date
          example: "2024-01-20"
        specialRequests:
          type: string
          nullable: true
          example: "Late check-in please"

    RejectionReasonDTO:
      type: object
      required:
        - reason
      properties:
        reason:
          type: string
          example: "Room not available for selected dates"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
        status:
          type: integer
          example: 400
        timestamp:
          type: string
          format: date-time

