openapi: 3.0.3
info:
  title: My Hotel Assistant API - Statistics
  description: Statistics and analytics endpoints
  version: 1.0.0
  contact:
    name: API Support
    email: support@myhotelassistant.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.myhotelassistant.com
    description: Production server

tags:
  - name: Statistics
    description: Service statistics endpoints

paths:
  /management/stats:
    get:
      tags:
        - Statistics
      summary: Get service statistics
      description: Retrieve statistics for all services (Manager only)
      operationId: getStats
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved statistics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStat'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Manager role required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ServiceStat:
      type: object
      properties:
        serviceId:
          type: string
          example: "service123"
        serviceName:
          type: string
          example: "Room Cleaning"
        totalOrders:
          type: integer
          example: 100
        completedOrders:
          type: integer
          example: 85
        canceledOrders:
          type: integer
          example: 15
        totalRevenue:
          type: number
          format: double
          example: 4250.00
        averageRating:
          type: number
          format: double
          nullable: true
          example: 4.5

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
        status:
          type: integer
          example: 400
        timestamp:
          type: string
          format: date-time

